services:
  dpploy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dpploy
    restart: always
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    environment:
      - DATABASE_URL=postgres://dpploy:dpploypassword@localhost:5432/dpploy
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:16-alpine
    container_name: dpploy-db
    restart: always
    network_mode: host
    environment:
      - POSTGRES_USER=dpploy
      - POSTGRES_PASSWORD=dpploypassword
      - POSTGRES_DB=dpploy
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dpploy"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: dpploy-redis
    restart: always
    network_mode: host
    volumes:
      - ./redis:/data
